// 词库：默认 4 字成语，每条带 拼音 + 释义 + 标签（谜面系统，像汉兜）。
// 想改 5 字：把 ANSWERS 换成 5 字词条，并把 index.js / engine 的 WORD_LEN 改为 5 即可。
// 仅导出 .js（小程序 require .json 在部分基础库会挂）。
// 标签取值：'数字'(含数字) / '动物'(含动物) / '自然'(含风花山水日云海天等) / '褒' / '贬' / '中'(感情色彩)
module.exports = {
  ANSWERS: [
    { word: '一帆风顺', pinyin: 'yī fān fēng shùn', meaning: '比喻非常顺利，没有阻碍。', tags: ['自然', '褒'] },
    { word: '三心二意', pinyin: 'sān xīn èr yì', meaning: '犹豫不决，不专心。', tags: ['数字', '贬'] },
    { word: '五颜六色', pinyin: 'wǔ yán liù sè', meaning: '形容色彩繁多鲜艳。', tags: ['数字', '中'] },
    { word: '七上八下', pinyin: 'qī shàng bà xià', meaning: '形容心里慌乱不安。', tags: ['数字', '中'] },
    { word: '九牛一毛', pinyin: 'jiǔ niú yī máo', meaning: '极大数量中微不足道的一点。', tags: ['数字', '动物', '中'] },
    { word: '千军万马', pinyin: 'qiān jūn wàn mǎ', meaning: '形容雄壮的队伍或浩大的声势。', tags: ['数字', '动物', '中'] },
    { word: '风和日丽', pinyin: 'fēng hé rì lì', meaning: '微风和畅，阳光明丽（好天气）。', tags: ['自然', '褒'] },
    { word: '山清水秀', pinyin: 'shān qīng shuǐ xiù', meaning: '山水风景优美。', tags: ['自然', '褒'] },
    { word: '鸟语花香', pinyin: 'niǎo yǔ huā xiāng', meaning: '鸟鸣花香，形容春天美景。', tags: ['动物', '自然', '褒'] },
    { word: '春暖花开', pinyin: 'chūn nuǎn huā kāi', meaning: '春天气候温暖，百花盛开。', tags: ['自然', '褒'] },
    { word: '春华秋实', pinyin: 'chūn huá qiū shí', meaning: '春天开花秋天结果，比喻文采与德行或因果。', tags: ['自然', '褒'] },
    { word: '桃红柳绿', pinyin: 'táo hóng liǔ lǜ', meaning: '桃花红柳树绿，形容春景。', tags: ['自然', '褒'] },
    { word: '蓝天白云', pinyin: 'lán tiān bái yún', meaning: '蓝色的天白色的云，好天气。', tags: ['自然', '褒'] },
    { word: '画蛇添足', pinyin: 'huà shé tiān zú', meaning: '多此一举，反而坏事。', tags: ['动物', '贬'] },
    { word: '守株待兔', pinyin: 'shǒu zhū dài tù', meaning: '死守经验不知变通，妄想不劳而获。', tags: ['动物', '贬'] },
    { word: '亡羊补牢', pinyin: 'wáng yáng bǔ láo', meaning: '出错后及时补救还不算晚。', tags: ['动物', '中'] },
    { word: '对牛弹琴', pinyin: 'duì niú tán qín', meaning: '对不懂的人讲道理，白费口舌。', tags: ['动物', '贬'] },
    { word: '井底之蛙', pinyin: 'jǐng dǐ zhī wā', meaning: '比喻眼界狭小的人。', tags: ['动物', '贬'] },
    { word: '狐假虎威', pinyin: 'hú jiǎ hǔ wēi', meaning: '倚仗别人势力欺压人。', tags: ['动物', '贬'] },
    { word: '叶公好龙', pinyin: 'yè gōng hào lóng', meaning: '表面爱好某物实际并非真爱。', tags: ['动物', '贬'] },
    { word: '杯弓蛇影', pinyin: 'bēi gōng shé yǐng', meaning: '疑神疑鬼，自相惊扰。', tags: ['动物', '贬'] },
    { word: '望梅止渴', pinyin: 'wàng méi zhǐ kě', meaning: '用空想安慰自己。', tags: ['中'] },
    { word: '掩耳盗铃', pinyin: 'yǎn ěr dào líng', meaning: '自欺欺人。', tags: ['贬'] },
    { word: '自相矛盾', pinyin: 'zì xiāng máo dùn', meaning: '言行前后抵触。', tags: ['贬'] },
    { word: '刻舟求剑', pinyin: 'kè zhōu qiú jiàn', meaning: '拘泥成法不知变通。', tags: ['贬'] },
    { word: '滥竽充数', pinyin: 'làn yú chōng shù', meaning: '无本领混在行家里充数。', tags: ['贬'] },
    { word: '愚公移山', pinyin: 'yú gōng yí shān', meaning: '比喻坚持不懈终能成功。', tags: ['褒'] },
    { word: '精卫填海', pinyin: 'jīng wèi tián hǎi', meaning: '比喻意志坚定不畏艰难。', tags: ['自然', '褒'] },
    { word: '开天辟地', pinyin: 'kāi tiān pì dì', meaning: '开创前所未有的伟大事业。', tags: ['自然', '褒'] },
    { word: '八仙过海', pinyin: 'bā xiān guò hǎi', meaning: '各自施展本领。', tags: ['数字', '自然', '中'] },
    { word: '火眼金睛', pinyin: 'huǒ yǎn jīn jīng', meaning: '眼光锐利能辨真伪。', tags: ['褒'] },
    { word: '三头六臂', pinyin: 'sān tóu liù bì', meaning: '形容本领大、办法多。', tags: ['数字', '中'] },
    { word: '呼风唤雨', pinyin: 'hū fēng huàn yǔ', meaning: '能够支配自然，比喻势力大。', tags: ['自然', '中'] },
    { word: '腾云驾雾', pinyin: 'téng yún jià wù', meaning: '形容奔驰迅速或恍惚迷离。', tags: ['自然', '中'] },
    { word: '七零八落', pinyin: 'qī líng bà luò', meaning: '零散不整齐。', tags: ['数字', '中'] },
    { word: '乱七八糟', pinyin: 'luàn qī bā zāo', meaning: '混乱不堪。', tags: ['数字', '贬'] },
    { word: '五光十色', pinyin: 'wǔ guāng shí sè', meaning: '色彩鲜艳花样多。', tags: ['数字', '中'] },
    { word: '万紫千红', pinyin: 'wàn zǐ qiān hóng', meaning: '百花齐放色彩绚丽，也比喻事物丰富。', tags: ['数字', '自然', '褒'] },
    { word: '五彩缤纷', pinyin: 'wǔ cǎi bīn fēn', meaning: '色彩繁多艳丽。', tags: ['数字', '中'] },
    { word: '花团锦簇', pinyin: 'huā tuán jǐn cù', meaning: '花朵锦绣簇拥，形容五彩缤纷。', tags: ['自然', '褒'] },
    { word: '姹紫嫣红', pinyin: 'chà zǐ yān hóng', meaning: '各种花朵娇艳。', tags: ['自然', '褒'] },
    { word: '山崩地裂', pinyin: 'shān bēng dì liè', meaning: '形容声势巨大或变化剧烈。', tags: ['自然', '中'] },
    { word: '风平浪静', pinyin: 'fēng píng làng jìng', meaning: '平静无事。', tags: ['自然', '中'] },
    { word: '人山人海', pinyin: 'rén shān rén hǎi', meaning: '人极多。', tags: ['自然', '中'] },
    { word: '千姿百态', pinyin: 'qiān zī bǎi tài', meaning: '姿态多种多样。', tags: ['数字', '中'] },
    { word: '神来之笔', pinyin: 'shén lái zhī bǐ', meaning: '绝妙、意想不到的精彩笔墨。', tags: ['褒'] },
    { word: '不可思议', pinyin: 'bù kě sī yì', meaning: '无法想象，难以理解。', tags: ['中'] },
    { word: '浩如烟海', pinyin: 'hào rú yān hǎi', meaning: '文献、资料等极其丰富。', tags: ['自然', '中'] },
    { word: '源源不断', pinyin: 'yuán yuán bù duàn', meaning: '连续不断。', tags: ['中'] },
    { word: '胸有成竹', pinyin: 'xiōng yǒu chéng zhú', meaning: '做事前已有通盘考虑，很有把握。', tags: ['褒'] },
    { word: '一丝不苟', pinyin: 'yī sī bù gǒu', meaning: '办事认真，一点儿不马虎。', tags: ['数字', '褒'] },
    { word: '聚精会神', pinyin: 'jù jīng huì shén', meaning: '集中精神，专心致志。', tags: ['褒'] },
    { word: '全神贯注', pinyin: 'quán shén guàn zhù', meaning: '全部精神集中。', tags: ['褒'] },
    { word: '废寝忘食', pinyin: 'fèi qǐn wàng shí', meaning: '专心努力到忘记饮食休息。', tags: ['褒'] },
    { word: '大公无私', pinyin: 'dà gōng wú sī', meaning: '完全为人民利益，毫无私心。', tags: ['褒'] },
    { word: '舍己为人', pinyin: 'shě jǐ wèi rén', meaning: '牺牲自己利益为他人。', tags: ['褒'] },
    { word: '助人为乐', pinyin: 'zhù rén wéi lè', meaning: '以帮助别人为快乐。', tags: ['褒'] },
    { word: '见义勇为', pinyin: 'jiàn yì yǒng wéi', meaning: '看到正义事就勇敢去做。', tags: ['褒'] },
    { word: '百折不挠', pinyin: 'bǎi zhé bù náo', meaning: '无论受多少挫折都不屈服。', tags: ['数字', '褒'] },
    { word: '锲而不舍', pinyin: 'qiè ér bù shě', meaning: '坚持不懈。', tags: ['褒'] },
    { word: '持之以恒', pinyin: 'chí zhī yǐ héng', meaning: '长期坚持下去。', tags: ['褒'] },
    { word: '孜孜不倦', pinyin: 'zī zī bù juàn', meaning: '勤勉不知疲倦。', tags: ['褒'] },
    { word: '全力以赴', pinyin: 'quán lì yǐ fù', meaning: '用尽全部力量。', tags: ['褒'] },
    { word: '争分夺秒', pinyin: 'zhēng fēn duó miǎo', meaning: '抓紧时间。', tags: ['中'] },
    { word: '日新月异', pinyin: 'rì xīn yuè yì', meaning: '发展变化快。', tags: ['自然', '褒'] },
    { word: '突飞猛进', pinyin: 'tū fēi měng jìn', meaning: '进步迅速。', tags: ['褒'] },
    { word: '一日千里', pinyin: 'yī rì qiān lǐ', meaning: '进展极快。', tags: ['数字', '自然', '褒'] },
    { word: '马到成功', pinyin: 'mǎ dào chéng gōng', meaning: '一开始就取得胜利。', tags: ['动物', '褒'] },
    { word: '水到渠成', pinyin: 'shuǐ dào qú chéng', meaning: '条件成熟自然成功。', tags: ['自然', '中'] },
    { word: '顺理成章', pinyin: 'shùn lǐ chéng zhāng', meaning: '合乎逻辑自然产生。', tags: ['中'] },
    { word: '理所当然', pinyin: 'lǐ suǒ dāng rán', meaning: '按道理应当如此。', tags: ['中'] },
    { word: '名正言顺', pinyin: 'míng zhèng yán shùn', meaning: '名义正当说话才有分量。', tags: ['中'] },
    { word: '义正词严', pinyin: 'yì zhèng cí yán', meaning: '理由正当措辞严肃。', tags: ['中'] },
    { word: '中流砥柱', pinyin: 'zhōng liú dǐ zhù', meaning: '坚强独立起支柱作用的人或力量。', tags: ['褒'] },
    { word: '坚持不懈', pinyin: 'jiān chí bù xiè', meaning: '坚持到底不松懈。', tags: ['褒'] },
    { word: '形形色色', pinyin: 'xíng xíng sè sè', meaning: '各种各样，种类很多。', tags: ['中'] },
    { word: '生生不息', pinyin: 'shēng shēng bù xī', meaning: '不断地生长繁殖。', tags: ['中'] },
    { word: '津津有味', pinyin: 'jīn jīn yǒu wèi', meaning: '特别有滋味、有兴趣。', tags: ['中'] },
    { word: '井井有条', pinyin: 'jǐng jǐng yǒu tiáo', meaning: '条理分明。', tags: ['褒'] },
    { word: '息息相关', pinyin: 'xī xī xiāng guān', meaning: '关系极为密切。', tags: ['中'] },
    { word: '默默无闻', pinyin: 'mò mò wú wén', meaning: '没有名声，不为人知。', tags: ['中'] },
    { word: '滔滔不绝', pinyin: 'tāo tāo bù jué', meaning: '话多连续不断。', tags: ['中'] },
    { word: '彬彬有礼', pinyin: 'bīn bīn yǒu lǐ', meaning: '文雅有礼貌。', tags: ['褒'] },
    { word: '栩栩如生', pinyin: 'xǔ xǔ rú shēng', meaning: '艺术形象生动逼真。', tags: ['褒'] },
    { word: '翩翩起舞', pinyin: 'piān piān qǐ wǔ', meaning: '轻快地跳舞。', tags: ['中'] },
    { word: '亭亭玉立', pinyin: 'tíng tíng yù lì', meaning: '女子身材修长挺拔。', tags: ['褒'] },
    { word: '依依不舍', pinyin: 'yī yī bù shě', meaning: '十分留恋不忍离开。', tags: ['数字', '中'] },
    { word: '恋恋不舍', pinyin: 'liàn liàn bù shě', meaning: '舍不得离开。', tags: ['中'] },
    { word: '津津乐道', pinyin: 'jīn jīn lè dào', meaning: '很有兴趣地谈论。', tags: ['中'] },
    { word: '咄咄逼人', pinyin: 'duō duō bī rén', meaning: '气势汹汹，盛气凌人。', tags: ['贬'] },
    { word: '济济一堂', pinyin: 'jǐ jǐ yī táng', meaning: '许多有才能的人聚在一起。', tags: ['中'] },
    { word: '历历在目', pinyin: 'lì lì zài mù', meaning: '情景清清楚楚地重现在眼前。', tags: ['中'] },
    { word: '振振有词', pinyin: 'zhèn zhèn yǒu cí', meaning: '理由似乎很充分地说个不停（多含贬义）。', tags: ['贬'] },
    { word: '落落大方', pinyin: 'luò luò dà fāng', meaning: '举止自然不拘束。', tags: ['褒'] },
    { word: '炯炯有神', pinyin: 'jiǒng jiǒng yǒu shén', meaning: '目光明亮有精神。', tags: ['中'] },
    { word: '步步为营', pinyin: 'bù bù wéi yíng', meaning: '行动谨慎，防守严密。', tags: ['中'] },
    { word: '比比皆是', pinyin: 'bǐ bǐ jiē shì', meaning: '到处都是，极其常见。', tags: ['中'] },
    { word: '格格不入', pinyin: 'gé gé bù rù', meaning: '彼此不协调、不相容。', tags: ['中'] },
    { word: '心心相印', pinyin: 'xīn xīn xiāng yìn', meaning: '彼此心意一致、感情相通。', tags: ['中'] },
    { word: '头头是道', pinyin: 'tóu tóu shì dào', meaning: '说话做事很有条理、道理充分。', tags: ['中'] },
    { word: '三三两两', pinyin: 'sān sān liǎng liǎng', meaning: '三个一群两个一伙。', tags: ['数字', '中'] },
    { word: '洋洋得意', pinyin: 'yáng yáng dé yì', meaning: '得意的样子（多含贬义）。', tags: ['贬'] },
    { word: '沾沾自喜', pinyin: 'zhān zhān zì xǐ', meaning: '自以为好而得意（贬义）。', tags: ['贬'] },
    { word: '欣欣向荣', pinyin: 'xīn xīn xiàng róng', meaning: '草木茂盛，比喻事业兴旺。', tags: ['褒'] },
    { word: '蒸蒸日上', pinyin: 'zhēng zhēng rì shàng', meaning: '事业一天天向上。', tags: ['褒'] }
  ]
};
